### ISSUE TITLE
Clustering process giving lesser number of point than input given

### ISSUE THREAD

**Issue by abhismatrix1** [SushantKafle/DBSCAN#2]
Hi SK,
Thanks for the update .

Now the problem is I am only getting 183 output including noise for input of 251 points.

csv file i used can be accessed from google drive if you want to have a look.
https://drive.google.com/open?id=0B2COuEGmtg4Rd0pNa1JHQjRGa28

(I used eps of .5)

**Comment by SushantKafle** [comment]
Hi again,

That probably happened because of repeating points in the csv file. I will `id` each point in the csv file during the read. I think this will fix the problem.

Check back again in few minutes. Thanks!

**Comment by SushantKafle** [comment]
Let me know if I can close this issue.

**Comment by abhismatrix1** [comment]
Now the output is random. Doesn't look like clustering
<img width="637" alt="screen shot 2017-07-14 at 10 26 57 pm" src="https://user-images.githubusercontent.com/27145212/28222168-e1d7ab9c-68e3-11e7-8a49-9136c8035ecf.png">

**Comment by SushantKafle** [comment]
Pushed some changes. Could you check if it helps?

**Comment by abhismatrix1** [comment]
Now things are better. But with same parameters sklearn DBSCAN gives more cluster.  As can be seen in attached  picture that there are close points which can become cluster but appearing as noise
<img width="616" alt="screen shot 2017-07-14 at 11 23 01 pm" src="https://user-images.githubusercontent.com/27145212/28224077-6c98462c-68eb-11e7-8fbf-26220be31406.png">

**Comment by SushantKafle** [comment]
Made the final changes for today. Please report any further issues you have with the code. I'll try to resolve them tomorrow.
